<?php
/**
 * Implements hook_enable().
 */
function rmg_tealium_update_7001() {
  // Make the rmg_tealium module invoke last.
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'rmg_tealium', '=')
    ->execute();

}

/**
 * Implements hook_enable().
 */
function rmg_tealium_install() {
  // Make the rmg_tealium module invoke last.
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'rmg_tealium', '=')
    ->execute();

}