<?php
/**
 * Implements hook_install().
 */
function tealium_install() {

  // Set javascript scope in precontent.
  variable_set('tealium_javascript_scope_theme', 'precontent');

  // Make the tealium module invoke last.
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'tealium', '=')
    ->execute();

}

/**
 * Implements hook_uninstall().
 */
function tealium_uninstall() {
  variable_del('tealium_javascript_scope_theme');
}